### ISSUE TITLE
Error in POD docs for Group::Git::Bitbucket

### ISSUE THREAD

**Issue by chrestomanci** [ivanwills/Group-Git#1]
Hello, While attempting to follow the example in the POD docs for Group::Git::Bitbucket, I have found that they don't work.

Stepping through with a debugger it is clear that the pull method expects the name of the repo to clone or pull, and you can get a list of repos in a BitBucket account with the repos() method. I think your example code should read something like:

``` perl
my $group = Group::Git::Bitbucket->new( conf => {
    username => 'joeblogs@gmail.com',
    password => 'myverysecurepassword',
} );

$repoList =  $group->repos();

foreach my $repoName ( keys %$repoList )
{
    print "Updating repo $repoName\n";
    my $result = $group->pull($repoName);
}
```

**Comment by ivanwills** [comment]
Hmm, looks like I haven't been very good with the documentation in general I'll fix this and more.

Thanks.

PS Are you a DWJ fan?

**Comment by chrestomanci** [comment]
Happy to help.

Not really a fan. I just read her books when I was a twelve and I guess they made an impression.
